import { useState } from 'react'
import { ArrowLeft, Award, Check, Download, ExternalLink, Share2, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CertificatePreview } from '../components/CertificatePreview'
import { certificateHistory } from '../data/accounting'

export function CertificatePage() {
  const [notice, setNotice] = useState('')
  const earnedCertificate = certificateHistory.find((certificate) => certificate.status === 'Đã đạt') ?? certificateHistory[0]
  const currentCertificate = certificateHistory.find((certificate) => certificate.status === 'Đang tiến tới')

  const showNotice = (message: string) => {
    setNotice(message)
    window.setTimeout(() => setNotice(''), 2800)
  }

  return (
    <section className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-14 lg:px-10 lg:py-20">
      <div className="flex flex-wrap items-center justify-between gap-4"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-slate-900 dark:text-slate-400 dark:hover:text-white"><ArrowLeft size={15} /> Dashboard học tập</Link><span className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-amber-600 dark:text-amber-300"><Award size={15} /> Certificate center</span></div>
      <div className="mt-10 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700 dark:text-teal-300">Completion records</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-5xl dark:text-white">Chứng chỉ hoàn thành</h1><p className="mt-5 text-base leading-8 text-slate-500 dark:text-slate-400">Lưu lại những level bạn đã hoàn thành và theo dõi mốc tiếp theo trong hành trình nâng cao năng lực AI cho Kế toán.</p></div>
      <div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_340px] lg:items-start"><div><CertificatePreview certificate={earnedCertificate} /><div className="mt-5 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => showNotice('Đã tạo bản tải chứng chỉ giả lập cho bạn.')} className="inline-flex flex-1 items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-3.5 text-sm font-semibold text-white transition hover:bg-teal-700 dark:bg-teal-300 dark:text-slate-950 dark:hover:bg-teal-200"><Download size={16} /> Tải chứng chỉ</button><button type="button" onClick={() => showNotice('Đã tạo liên kết chia sẻ giả lập.')} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 px-5 py-3.5 text-sm font-semibold text-slate-700 transition hover:border-teal-300 hover:text-teal-700 dark:border-slate-800 dark:text-slate-200"><Share2 size={16} /> Chia sẻ</button></div>{notice && <div className="mt-4 flex items-center gap-2 rounded-2xl border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-800 dark:border-teal-900/70 dark:bg-teal-950/30 dark:text-teal-200"><Check size={16} /> {notice}</div>}</div><aside className="rounded-3xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2 text-sm font-semibold text-slate-900 dark:text-white"><Sparkles size={18} className="text-teal-600" /> Mốc tiếp theo</div>{currentCertificate && <><p className="mt-6 text-xs font-bold uppercase tracking-[0.14em] text-slate-400">{currentCertificate.level}</p><h2 className="mt-2 text-xl font-semibold text-slate-900 dark:text-white">{currentCertificate.title}</h2><div className="mt-6 flex items-end justify-between text-sm"><span className="text-slate-500 dark:text-slate-400">Tiến độ hiện tại</span><strong className="text-teal-700 dark:text-teal-300">{currentCertificate.progress}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-teal-600 dark:bg-teal-300" style={{ width: `${currentCertificate.progress}%` }} /></div><p className="mt-4 text-sm leading-6 text-slate-500 dark:text-slate-400">Hoàn thành toàn bộ video và bài đánh giá để mở chứng chỉ level tiếp theo.</p><Link to="/roadmap" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-teal-700 dark:text-teal-300">Xem lộ trình học <ExternalLink size={15} /></Link></>}</aside></div>
      <div className="mt-14"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700 dark:text-teal-300">Certificate history</p><h2 className="mt-3 text-2xl font-semibold tracking-tight text-slate-900 sm:text-3xl dark:text-white">Lịch sử chứng chỉ</h2></div><span className="rounded-full bg-teal-50 px-3 py-1.5 text-xs font-bold text-teal-700 dark:bg-teal-950/60 dark:text-teal-300">{certificateHistory.filter((item) => item.status === 'Đã đạt').length} đã đạt</span></div><div className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">{certificateHistory.map((certificate) => <div key={certificate.id} className="flex flex-col gap-4 border-b border-slate-100 p-5 last:border-0 sm:flex-row sm:items-center dark:border-slate-800"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${certificate.status === 'Đã đạt' ? 'bg-amber-50 text-amber-600 dark:bg-amber-950/50 dark:text-amber-300' : 'bg-slate-100 text-slate-400 dark:bg-slate-800'}`}><Award size={20} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-900 dark:text-white">{certificate.title}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] ${certificate.status === 'Đã đạt' ? 'bg-teal-50 text-teal-700 dark:bg-teal-950/50 dark:text-teal-300' : 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400'}`}>{certificate.status}</span></div><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{certificate.level} · {certificate.issuedAt} · {certificate.certificateCode}</p></div>{certificate.status === 'Đã đạt' ? <button type="button" onClick={() => showNotice(`Đã chọn chứng chỉ ${certificate.certificateCode}.`)} className="inline-flex items-center gap-1.5 text-xs font-semibold text-teal-700 dark:text-teal-300">Xem chi tiết <ExternalLink size={14} /></button> : <Link to="/assessment" className="inline-flex items-center gap-1.5 text-xs font-semibold text-teal-700 dark:text-teal-300">Đánh giá ngay <ExternalLink size={14} /></Link>}</div>)}</div></div>
    </section>
  )
}
