import { ArrowRight, Award, BookOpen, CheckCircle2, Clock3, FileText, Flame, PlayCircle, Route, Sparkles, Target } from 'lucide-react'
import { Link } from 'react-router-dom'
import { AIChatbot } from '../components/AIChatbot'
import { Icon } from '../components/Icon'
import { LearningSuggestionCard } from '../components/LearningSuggestionCard'
import { ProgressInsightCard } from '../components/ProgressInsightCard'
import { RoadmapItemCard } from '../components/RoadmapItemCard'
import { SectionHeading } from '../components/SectionHeading'
import { accountingRoadmap } from '../data/accounting'
import { accountingLearningSuggestions, accountingVideos, recommendedAccountingTools } from '../data/roles'

export function DashboardPage() {
  return (
    <>
      <section className="relative overflow-hidden border-b border-slate-200/80 dark:border-slate-800/80">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_80%_0%,rgba(20,184,166,0.16),transparent_30%),linear-gradient(135deg,rgba(240,253,250,0.8),rgba(248,250,252,0.2))] dark:bg-[radial-gradient(circle_at_80%_0%,rgba(20,184,166,0.12),transparent_30%),linear-gradient(135deg,rgba(15,118,110,0.08),rgba(2,6,23,0.2))]" />
        <div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-8 sm:py-16 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:px-10 lg:py-20">
          <div>
            <div className="flex flex-wrap items-center gap-3"><div className="inline-flex items-center gap-2 rounded-full border border-teal-200 bg-white/70 px-3 py-1.5 text-xs font-semibold text-teal-800 backdrop-blur dark:border-teal-900 dark:bg-slate-900/70 dark:text-teal-300"><Sparkles size={14} /> Accounting learning dashboard</div><Link to="/framework" className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 transition hover:text-teal-700 dark:text-slate-400 dark:hover:text-teal-300">Cơ sở pháp lý & Khung năng lực số <ArrowRight size={13} /></Link></div>
            <h1 className="mt-6 max-w-2xl text-4xl font-semibold leading-[1.08] tracking-[-0.04em] text-slate-950 sm:text-5xl dark:text-white">Tiếp tục hành trình nâng cao năng lực AI.</h1>
            <p className="mt-5 max-w-xl text-base leading-8 text-slate-600 dark:text-slate-300">Bạn đang ở Level 2 · Practitioner. Hãy hoàn thành bài học về đối soát để tiến gần hơn đến khả năng tích hợp workflow.</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/dashboard/learn/ai-accounting-02" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-teal-700 px-5 py-3.5 text-sm font-semibold text-white shadow-xl shadow-teal-700/15 transition hover:-translate-y-0.5 hover:bg-teal-800 dark:bg-teal-300 dark:text-slate-950 dark:hover:bg-teal-200"><PlayCircle size={17} /> Tiếp tục học</Link><Link to="/assessment" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white/80 px-5 py-3.5 text-sm font-semibold text-slate-700 transition hover:border-teal-300 dark:border-slate-700 dark:bg-slate-900/70 dark:text-slate-200"><Target size={16} /> Đánh giá năng lực</Link></div>
          </div>
          <div className="rounded-[2rem] border border-white/80 bg-white/85 p-5 shadow-soft backdrop-blur-xl dark:border-slate-800 dark:bg-slate-900/85"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Your progress</p><p className="mt-2 text-lg font-semibold text-slate-900 dark:text-white">AI for Accounting</p></div><span className="text-3xl font-semibold text-teal-700 dark:text-teal-300">62%</span></div><div className="mt-7 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full w-[62%] rounded-full bg-teal-600 dark:bg-teal-300" /></div><div className="mt-5 grid grid-cols-3 gap-3"><div><p className="text-xs text-slate-400">Đã hoàn thành</p><p className="mt-1 font-semibold text-slate-800 dark:text-slate-100">1 / 5</p></div><div><p className="text-xs text-slate-400">Thời gian còn</p><p className="mt-1 font-semibold text-slate-800 dark:text-slate-100">42 phút</p></div><div><p className="text-xs text-slate-400">Streak</p><p className="mt-1 flex items-center gap-1 font-semibold text-slate-800 dark:text-slate-100">4 <Flame size={14} className="text-orange-500" /></p></div></div></div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Link to="/assessment" className="group rounded-3xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-teal-200 hover:shadow-soft dark:border-slate-800 dark:bg-slate-900"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-50 text-teal-700 dark:bg-teal-950/60 dark:text-teal-300"><Target size={19} /></span><p className="mt-5 text-sm font-semibold text-slate-900 dark:text-white">Đánh giá năng lực</p><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">8 câu hỏi theo bối cảnh Kế toán</p><ArrowRight size={15} className="mt-4 text-teal-600 transition group-hover:translate-x-1" /></Link><Link to="/roadmap" className="group rounded-3xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-teal-200 hover:shadow-soft dark:border-slate-800 dark:bg-slate-900"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-violet-700 dark:bg-violet-950/60 dark:text-violet-300"><Route size={19} /></span><p className="mt-5 text-sm font-semibold text-slate-900 dark:text-white">Lộ trình AI</p><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">5 bước ưu tiên theo level</p><ArrowRight size={15} className="mt-4 text-violet-600 transition group-hover:translate-x-1" /></Link><Link to="/certificate" className="group rounded-3xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-teal-200 hover:shadow-soft dark:border-slate-800 dark:bg-slate-900"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-600 dark:bg-amber-950/50 dark:text-amber-300"><Award size={19} /></span><p className="mt-5 text-sm font-semibold text-slate-900 dark:text-white">Chứng chỉ</p><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">Xem mốc đã hoàn thành</p><ArrowRight size={15} className="mt-4 text-amber-600 transition group-hover:translate-x-1" /></Link><Link to="/resources" className="group rounded-3xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-teal-200 hover:shadow-soft dark:border-slate-800 dark:bg-slate-900"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300"><FileText size={19} /></span><p className="mt-5 text-sm font-semibold text-slate-900 dark:text-white">Tài nguyên & công cụ</p><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">Template và AI stack</p><ArrowRight size={15} className="mt-4 text-blue-600 transition group-hover:translate-x-1" /></Link></div></section>

      <section className="mx-auto max-w-7xl px-5 pb-14 sm:px-8 lg:px-10 lg:pb-20"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-50 text-teal-700 dark:bg-teal-950/60 dark:text-teal-300"><BookOpen size={19} /></span><span className="text-xs font-medium uppercase tracking-[0.12em] text-slate-400">Lessons done</span></div><p className="mt-5 text-3xl font-semibold text-slate-900 dark:text-white">01</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">trong 05 video</p></div><div className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300"><Clock3 size={19} /></span><span className="text-xs font-medium uppercase tracking-[0.12em] text-slate-400">Learning time</span></div><p className="mt-5 text-3xl font-semibold text-slate-900 dark:text-white">2.4h</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">+35 phút tuần này</p></div><div className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-violet-700 dark:bg-violet-950/60 dark:text-violet-300"><CheckCircle2 size={19} /></span><span className="text-xs font-medium uppercase tracking-[0.12em] text-slate-400">Skills practiced</span></div><p className="mt-5 text-3xl font-semibold text-slate-900 dark:text-white">03</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">trên 06 kỹ năng</p></div></div></section>

      <section className="border-y border-slate-200/80 bg-white/70 dark:border-slate-800/80 dark:bg-slate-900/20"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><div className="grid gap-8 lg:grid-cols-[1.2fr_0.8fr] lg:items-start"><div><SectionHeading eyebrow="Personalized by AI" title="AI gợi ý học tập" description="Các bước tiếp theo được đề xuất từ tiến độ, kỹ năng ưu tiên và mục tiêu Level 3 của bạn." /><div className="mt-8 grid gap-4 md:grid-cols-3">{accountingLearningSuggestions.map((suggestion) => <LearningSuggestionCard key={suggestion.title} suggestion={suggestion} />)}</div></div><ProgressInsightCard /></div></div></section>

      <section id="ai-roadmap" className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading eyebrow="AI learning roadmap" title="Lộ trình AI đề xuất cho bạn" description="AI sắp xếp video và kỹ năng theo level hiện tại, kết quả đánh giá và khoảng cách cần ưu tiên." /><Link to="/roadmap" className="inline-flex w-fit items-center gap-2 text-sm font-semibold text-teal-700 hover:text-teal-800 dark:text-teal-300">Xem toàn bộ lộ trình <ArrowRight size={16} /></Link></div><div className="mt-8 grid gap-4 lg:grid-cols-3">{accountingRoadmap.slice(0, 3).map((item, index) => <RoadmapItemCard key={item.id} item={item} index={index} compact />)}</div></section>

      <section className="mx-auto max-w-7xl px-5 pb-14 sm:px-8 lg:px-10 lg:pb-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading eyebrow="Course playlist" title="Lộ trình video Kế toán" description="Học theo thứ tự gợi ý hoặc chọn một chủ đề phù hợp với nhu cầu công việc hiện tại." /><Link to="/dashboard/learn/ai-accounting-02" className="inline-flex w-fit items-center gap-2 text-sm font-semibold text-slate-700 hover:text-teal-700 dark:text-slate-300 dark:hover:text-teal-300">Mở trình học <ArrowRight size={16} /></Link></div><div className="mt-8 overflow-hidden rounded-3xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900/70">{accountingVideos.map((video, index) => <Link key={video.id} to={`/dashboard/learn/${video.id}`} className="group flex items-center gap-4 border-b border-slate-100 p-4 transition last:border-0 hover:bg-slate-50 sm:p-5 dark:border-slate-800 dark:hover:bg-slate-800/50"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${video.completed ? 'bg-teal-50 text-teal-700 dark:bg-teal-950/60 dark:text-teal-300' : 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-300'}`}>{video.completed ? <CheckCircle2 size={19} /> : <Icon name={video.icon} size={19} />}</span><span className="min-w-0 flex-1"><span className="block text-[11px] font-bold uppercase tracking-[0.14em] text-slate-400">{video.module}</span><span className="mt-1 block truncate text-sm font-semibold text-slate-900 dark:text-white">{video.title}</span></span><span className="hidden text-xs text-slate-400 sm:block">{video.duration}</span><ArrowRight size={16} className="text-slate-300 transition group-hover:translate-x-1 group-hover:text-teal-600" /></Link>)}</div></section>

      <section className="border-t border-slate-200/80 bg-white/70 dark:border-slate-800/80 dark:bg-slate-900/20"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading eyebrow="Recommended for your role" title="Công cụ AI khuyến nghị cho Kế toán" description="Bắt đầu từ nhóm công cụ gắn với dữ liệu, chứng từ và workflow. Luôn kiểm tra chính sách dữ liệu trước khi dùng." /><Link to="/resources" className="inline-flex w-fit items-center gap-2 text-sm font-semibold text-teal-700 dark:text-teal-300">Mở thư viện công cụ <ArrowRight size={16} /></Link></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{recommendedAccountingTools.map((tool) => <div key={tool.name} className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200"><Icon name={tool.icon} size={19} /></span><p className="mt-5 text-[10px] font-bold uppercase tracking-[0.14em] text-teal-700 dark:text-teal-300">{tool.category}</p><h3 className="mt-2 font-semibold text-slate-900 dark:text-white">{tool.name}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{tool.description}</p></div>)}</div></div></section>
      <AIChatbot />
    </>
  )
}
