import { useMemo, useState } from 'react'
import { ArrowLeft, BookOpen, Bot, Filter, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { AIToolCard, ResourceCard } from '../components/ResourceCard'
import { accountingResources, accountingToolRecommendations } from '../data/accounting'

type ResourceTab = 'resources' | 'tools'

export function ResourcesPage() {
  const [activeTab, setActiveTab] = useState<ResourceTab>('resources')
  const [levelFilter, setLevelFilter] = useState('Tất cả level')
  const [skillFilter, setSkillFilter] = useState('Tất cả kỹ năng')

  const skillOptions = useMemo(() => Array.from(new Set([...accountingResources.map((item) => item.skill), ...accountingToolRecommendations.map((item) => item.skill)])), [])
  const filteredResources = accountingResources.filter((item) => (levelFilter === 'Tất cả level' || item.levels.includes(levelFilter)) && (skillFilter === 'Tất cả kỹ năng' || item.skill === skillFilter))
  const filteredTools = accountingToolRecommendations.filter((item) => (levelFilter === 'Tất cả level' || item.levels.includes(levelFilter)) && (skillFilter === 'Tất cả kỹ năng' || item.skill === skillFilter))

  return (
    <section className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-14 lg:px-10 lg:py-20">
      <div className="flex flex-wrap items-center justify-between gap-4"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-slate-900 dark:text-slate-400 dark:hover:text-white"><ArrowLeft size={15} /> Dashboard học tập</Link><span className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-teal-700 dark:text-teal-300"><Sparkles size={14} /> Accounting resource hub</span></div>
      <div className="mt-10 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700 dark:text-teal-300">Resources & AI tools</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-5xl dark:text-white">Thư viện tài nguyên & Công cụ AI</h1><p className="mt-5 text-base leading-8 text-slate-500 dark:text-slate-400">Chọn tài liệu để thực hành hoặc khám phá công cụ theo level và kỹ năng. Mọi nội dung đều dùng dữ liệu mẫu và cần được rà soát theo chính sách của doanh nghiệp.</p></div>
      <div className="mt-10 flex flex-col gap-4 border-b border-slate-200 pb-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800"><div className="flex gap-2 overflow-x-auto"><button type="button" onClick={() => setActiveTab('resources')} className={`inline-flex shrink-0 items-center gap-2 rounded-2xl px-4 py-3 text-sm font-semibold transition ${activeTab === 'resources' ? 'bg-slate-950 text-white dark:bg-teal-300 dark:text-slate-950' : 'text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'}`}><BookOpen size={16} /> Tài liệu & Template <span className="rounded-full bg-white/15 px-2 py-0.5 text-[10px]">{filteredResources.length}</span></button><button type="button" onClick={() => setActiveTab('tools')} className={`inline-flex shrink-0 items-center gap-2 rounded-2xl px-4 py-3 text-sm font-semibold transition ${activeTab === 'tools' ? 'bg-slate-950 text-white dark:bg-teal-300 dark:text-slate-950' : 'text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800'}`}><Bot size={16} /> Công cụ AI khuyến nghị <span className="rounded-full bg-black/5 px-2 py-0.5 text-[10px] dark:bg-white/10">{filteredTools.length}</span></button></div><div className="flex items-center gap-2 text-xs text-slate-400"><Filter size={14} /> Bộ lọc đang áp dụng</div></div>
      <div className="mt-6 grid gap-3 rounded-3xl border border-slate-200 bg-white p-4 sm:grid-cols-2 dark:border-slate-800 dark:bg-slate-900"><label className="flex items-center gap-3 text-xs font-semibold text-slate-500 dark:text-slate-400"><span className="w-24 shrink-0">Theo level</span><select value={levelFilter} onChange={(event) => setLevelFilter(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-medium text-slate-700 outline-none focus:border-teal-400 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"><option>Tất cả level</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Expert</option></select></label><label className="flex items-center gap-3 text-xs font-semibold text-slate-500 dark:text-slate-400"><span className="w-24 shrink-0">Theo kỹ năng</span><select value={skillFilter} onChange={(event) => setSkillFilter(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-medium text-slate-700 outline-none focus:border-teal-400 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"><option>Tất cả kỹ năng</option>{skillOptions.map((skill) => <option key={skill}>{skill}</option>)}</select></label></div>
      <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{activeTab === 'resources' ? filteredResources.map((resource) => <ResourceCard key={resource.id} resource={resource} />) : filteredTools.map((tool) => <AIToolCard key={tool.id} tool={tool} />)}</div>{((activeTab === 'resources' && filteredResources.length === 0) || (activeTab === 'tools' && filteredTools.length === 0)) && <div className="mt-8 rounded-3xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500 dark:border-slate-700 dark:text-slate-400">Chưa có nội dung phù hợp với bộ lọc hiện tại. Hãy thử chọn level hoặc kỹ năng khác.</div>}
      <div className="mt-12 rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-teal-300"><Sparkles size={14} /> Practice safely</p><h2 className="mt-3 text-xl font-semibold">Bắt đầu với dữ liệu giả lập</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">AI chỉ nên hỗ trợ phân tích và ưu tiên tín hiệu. Hãy giữ bước xác minh, phê duyệt và ghi nhận quyết định của người chịu trách nhiệm.</p></div><Link to="/dashboard/learn/ai-accounting-02" className="inline-flex w-fit items-center justify-center rounded-2xl bg-teal-300 px-5 py-3.5 text-sm font-semibold text-slate-950 transition hover:bg-teal-200">Mở bài thực hành</Link></div></div>
    </section>
  )
}
