import { useState } from 'react'
import { ArrowLeft, Check, CheckCircle2, Clock3, Route, Sparkles, Target } from 'lucide-react'
import { Link } from 'react-router-dom'
import { RoadmapItemCard } from '../components/RoadmapItemCard'
import { accountingRoadmap } from '../data/accounting'

export function RoadmapPage() {
  const [isApplied, setIsApplied] = useState(false)

  return (
    <section className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-14 lg:px-10 lg:py-20">
      <div className="flex flex-wrap items-center justify-between gap-4"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-slate-900 dark:text-slate-400 dark:hover:text-white"><ArrowLeft size={15} /> Dashboard học tập</Link><span className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-teal-700 dark:text-teal-300"><Sparkles size={14} /> AI personalized roadmap</span></div>
      <div className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700 dark:text-teal-300">AI Learning Roadmap</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-5xl dark:text-white">Lộ trình AI đề xuất cho bạn</h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-500 dark:text-slate-400">Lộ trình được sắp xếp theo level hiện tại, kết quả đánh giá gần nhất và những kỹ năng Kế toán cần ưu tiên để tiến tới Level 3.</p></div><div className="rounded-[2rem] bg-slate-950 p-6 text-white shadow-soft"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-teal-300"><Route size={15} /> Current track</span><span className="rounded-full bg-teal-300 px-2.5 py-1 text-[10px] font-bold text-slate-950">AI matched</span></div><div className="mt-6 flex items-end justify-between"><div><p className="text-xs text-slate-400">Level hiện tại</p><p className="mt-1 text-xl font-semibold">Level 2 · Practitioner</p></div><p className="text-3xl font-semibold text-teal-300">62%</p></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-[62%] rounded-full bg-teal-300" /></div><p className="mt-3 text-xs leading-5 text-slate-400">Mục tiêu tiếp theo: Level 3 · Integrator</p></div></div>
      <div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-50 text-teal-700 dark:bg-teal-950/60 dark:text-teal-300"><Target size={19} /></span><p className="mt-5 text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Focus area</p><p className="mt-2 font-semibold text-slate-900 dark:text-white">Data control & workflow</p></div><div className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300"><Clock3 size={19} /></span><p className="mt-5 text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Estimated time</p><p className="mt-2 font-semibold text-slate-900 dark:text-white">61 phút · 5 bài học</p></div><div className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-violet-700 dark:bg-violet-950/60 dark:text-violet-300"><Sparkles size={19} /></span><p className="mt-5 text-xs font-bold uppercase tracking-[0.14em] text-slate-400">AI rationale</p><p className="mt-2 font-semibold text-slate-900 dark:text-white">Ưu tiên kỹ năng có thể áp dụng ngay</p></div></div>
      <div className="mt-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700 dark:text-teal-300">Recommended sequence</p><h2 className="mt-3 text-2xl font-semibold tracking-tight text-slate-900 sm:text-3xl dark:text-white">Thứ tự học được AI đề xuất</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-500 dark:text-slate-400">Mỗi bước nêu rõ lý do đề xuất, thời lượng và kỹ năng đích để bạn chủ động điều chỉnh.</p></div><button type="button" onClick={() => setIsApplied((current) => !current)} className={`inline-flex w-fit items-center justify-center gap-2 rounded-2xl px-5 py-3.5 text-sm font-semibold transition ${isApplied ? 'bg-teal-50 text-teal-700 dark:bg-teal-950/60 dark:text-teal-300' : 'bg-slate-950 text-white hover:bg-teal-700 dark:bg-teal-300 dark:text-slate-950 dark:hover:bg-teal-200'}`}>{isApplied ? <Check size={16} /> : <Sparkles size={16} />}{isApplied ? 'Đã áp dụng lộ trình' : 'Áp dụng lộ trình này'}</button></div>
      {isApplied && <div className="mt-6 flex items-start gap-3 rounded-2xl border border-teal-200 bg-teal-50 p-4 text-sm leading-6 text-teal-900 dark:border-teal-900/70 dark:bg-teal-950/30 dark:text-teal-100"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-teal-600" /><p><strong>Lộ trình đã được áp dụng.</strong> Dashboard sẽ ưu tiên các bài học này trong phiên MVP hiện tại.</p></div>}
      <div className="mt-8 space-y-4">{accountingRoadmap.map((item, index) => <RoadmapItemCard key={item.id} item={item} index={index} />)}</div>
      <div className="mt-10 rounded-3xl border border-slate-200 bg-white p-5 text-sm leading-7 text-slate-500 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-400"><strong className="text-slate-800 dark:text-slate-200">Cách AI đề xuất:</strong> kết hợp tiến độ video, kết quả đánh giá, level mục tiêu và yêu cầu kiểm soát dữ liệu trong công việc Kế toán. Bạn vẫn có thể học theo nhu cầu thực tế của mình.</div>
    </section>
  )
}
